name: redhat-datagrid-video
services:
  database:
    container_name: MySQL
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redHatDataGridVideo
    volumes:
      #     - data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    command:
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -proot" ]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    container_name: phpMyAdmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      database:
        condition: service_healthy
    links:
      - database

volumes:
  data: